name: rust-clippy-check

on:
  pull_request:
    branches:
      - main

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  rust-clippy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rust-clippy-check
        run: cargo clippy --all-targets --all-features --tests