name: rust-test-check

on:
  pull_request:
    branches:
      - main

jobs:
  rust-test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
      # - name: Cache cargo
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: ${{ runner.os }}-rust-test-check-${{ hashFiles('**/Cargo.lock') }}
      #     restore-keys: ${{ runner.os }}-rust-test-check-${{ hashFiles('**/Cargo.lock') }}
      - name: rust-test-check
        run: cargo +nightly test