name: rust-test-check

on:
  pull_request:
    branches:
      - main

jobs:
  rust-test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rust-test-check
        run: cargo test